In [10]:
import numpy as np
import pandas as pd

merhaba


In [11]:
a=5
b=8
print("merhaba")
print(a+b)

merhaba
38


In [12]:
l1=[3,5,8,20]
l2=[[3,5],[4,8]]

In [13]:
np1=np.array([1,2,3,4,5,6,7])

In [15]:
np1+1

array([2, 3, 4, 5, 6, 7, 8])

In [16]:
np1*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [18]:
dizi = np.array([1,2,3,4,5,6,7,8,9,10])

In [19]:
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
dizi.shape #dizinin şekli shape ile öğrenilir. bu dizi elemanlı bir dizidir. 

(10,)

In [21]:
dizi.ndim # bu komut dizinin kaç boyutlu olduğub bilgisini verir. Bu dizi 1 boyutlu bir dizidir.

1

In [22]:
dizi.size # dizideki eleman sayısını verir.

10

In [25]:
# numpy dizilerinde(ndarray) veri tipleri aynı olmalıdır.
dizi.dtype.name # bu ilgi dizinin veri tipini bize döbndürür

'int64'

In [32]:
dizi2=np.array([[3,5,12,-1],[8,2,22,88]])
dizi2

array([[ 3,  5, 12, -1],
       [ 8,  2, 22, 88]])

In [33]:
dizi2.shape

(2, 4)

In [37]:
print("size",dizi2.size)
print("shape",dizi2.shape)
print("ndim",dizi2.ndim)

size 8
shape (2, 4)
ndim 2


In [40]:
print("en büyük",dizi2.max())
print("en küçük",dizi2.min())
print("değerler toplamı",dizi2.sum())

en büyük 88
en küçük -1
değerler toplamı 139


In [42]:
print("sütunlar toplamı=",dizi2.sum(axis=0))
print("satırlar  toplamı=",dizi2.sum(axis=1))

sütunlar toplamı= [11  7 34 87]
satırlar  toplamı= [ 19 120]


In [44]:
print("ilk sütun değerleri toplamı",dizi2.sum(axis=0)[0])

ilk sütun değerleri toplamı 11


In [46]:
# zeros komutu istediğim shape yapısında sıfırlardan oluşan bir ndarray oluşturur
dizi_0 = np.zeros((10,8))# 10 satır 8 sütundan oluşan bir sıfırlar matrisi
dizi_0

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
dizi_1=np.ones((4,5))
dizi_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
dizi_9=dizi_1+8
dizi_9

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])