In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [27]:
veri = pd.read_csv("telefon_fiyatlari.csv")
veri

Telefon kodu  RAM Kapasitesi  Dahili hafiza    Ekran Tipi   Fiyat
0            T1               4            128  SUPER AMOLED  3300.0
1            T2               6            256        AMOLED  4400.0
2            T3               4            128        AMOLED  2700.0
3            T4               6            128           IPS  3600.0
4            T5               6             64           IPS  3200.0
5            T6               8            128  SUPER AMOLED  4100.0
6            T7               4             64        AMOLED  2400.0
7            T8               4             64  SUPER AMOLED  3000.0
8            T9               8            256           IPS  4200.0
9           T10               6            256           IPS     NaN
10          T11               8            128        AMOLED     NaN

In [28]:
# SUPER AMOLED=3, AMOLED=2, IPS=1
# replace komutus
veri["Ekran Tipi"].replace(to_replace=["SUPER AMOLED", "AMOLED", "IPS"], value=[0, 1, 2] , inplace=True)
veri

Telefon kodu  RAM Kapasitesi  Dahili hafiza  Ekran Tipi   Fiyat
0            T1               4            128           0  3300.0
1            T2               6            256           1  4400.0
2            T3               4            128           1  2700.0
3            T4               6            128           2  3600.0
4            T5               6             64           2  3200.0
5            T6               8            128           0  4100.0
6            T7               4             64           1  2400.0
7            T8               4             64           0  3000.0
8            T9               8            256           2  4200.0
9           T10               6            256           2     NaN
10          T11               8            128           1     NaN

In [29]:
# sklearn verileri numpy dizisi olarak ister
# sklearn verileri 2 boyutlu olarak ister
x_egitim=veri.iloc[0:9,1:4].values
y_egitim = veri.iloc[0:9,4].values.reshape(-1,1)
x_tahmin=veri.iloc[9:,1:4].values

In [38]:
model = LinearRegression()# model adında bir linearRegression modeli oluşturdum.
model.fit(x_egitim,y_egitim)
#model eldeki x_egitim ve y_egitim verileri ile eğitilmiş bir makine öğrenmesi modeli oluşturdu

LinearRegression()

In [31]:
#y=ax1+bx2+cx3+d
#x1=ram, x2=depolama alanı, x3=ekran tipi ,
# model bu fonksiyondaki a,b,c ve d değerlerini hesapladı
# a,b,c değerleri coef_ ile görüntülenir
print(model.coef_)
# d x değerleri 0 iken d değeri de intercept_
print(model.intercept_)

[[ 251.78571429    4.85491071 -171.42857143]]
[1550.]


In [36]:
model.predict([[4,128,1]])

array([[3007.14285714]])

In [33]:
model.score(x_egitim,y_egitim)

0.8806439674315322

In [35]:
model.predict(x_tahmin)

array([[3960.71428571],
       [4014.28571429]])

In [37]:
from joblib import dump,load

In [39]:
dump(model,"telefon_tahmin.joblib")

['telefon_tahmin.joblib']

In [40]:
m=load("telefon_tahmin.joblib")

In [41]:
m.predict([[8,128,2]])

array([[3842.85714286]])